{
	"version": 1639464298,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"offlineClient.js",
		"images/imageobject-sheet0.png",
		"images/imageobject-sheet1.png",
		"images/gameoverbackground-sheet0.png",
		"images/imageobject2-sheet0.png",
		"images/imageobject2-sheet1.png",
		"images/spritefont.png",
		"images/imageobject01-sheet0.png",
		"images/tryagainbackground-sheet0.png",
		"media/wrong.m4a",
		"media/wrong.ogg",
		"media/wrong3.m4a",
		"media/wrong3.ogg",
		"media/wrong2.m4a",
		"media/wrong5.ogg",
		"media/wrong4.m4a",
		"media/wrong4.ogg",
		"media/android2.m4a",
		"media/android2.ogg",
		"media/gameover1.m4a",
		"media/gameover1.ogg",
		"media/newachievement1.m4a",
		"media/newachievement1.ogg",
		"media/gameover2.m4a",
		"media/gameover2.ogg",
		"media/timp1.m4a",
		"media/timp1.ogg",
		"media/sword swing.m4a",
		"media/sword swing.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}